---
title: "The Sum of a Magic Square of Squares Can't be an Even-Power"
author: "Hyun Joon"
date: "2026-05-10"
categories: ["magic squares"]
format: html
---

# Motivation
After looking at the results from the code. One can guess that there isn't a 3x3 magic square of squares whose sum is a perfect square.
At first this seemed very hard to prove, well that is until a fun fact about all 3 by 3 magic squares share
That its sum is equal to 3 times the number in the center.
With this simple fact a simple proof by contradiction would seem to work best, for we leverage the irrationality of the square root of 3.  
But first, we'll have to prove that the sum of any 3x3 magic square really is 3 times its center number

## The Proof for the Fun Fact

For any 3 by 3 magic square the sum is equal to 3 times its center value. This surprising is pretty simple to prove.
First, an arbitrary 3x3 magic square:
$$
\begin{array}{c|c|c}
A & B & C \\ \hline
D & E & F \\ \hline
G & H & I
\end{array}
$$  
Now because this is a magic square its elements, in each row, column, and diagonal, when summed adds to a single value. Let's call this value S.  
\begin{align*}
&\text{So, we have}\\
&A + B + C = S,\ D + E + F = S,\ G + H + I = S\ \text{for each row}\\
&A + D + G = S,\ B + E + H = S,\ C + F + I = S\ \text{for each column}\\
&A + E + I = S,\ C + E + G = S\ \text{for each diagonal}\\
\end{align*}

Now, take the four equations
\begin{align*}
D + E + F = S \\ A + E + I = S \\ B + E + H = S \\ C + E + G = S
\end{align*}  
Observe that
\begin{align*}
4S &= (D + E + F) + (A + E + I) + (B + E + H) + (C + E + G)\\
&= D + E + F + A + E + I + B + E + H + C + E + G
\end{align*}  
Suggestively rewrite the right most side and left most side, and collect like terms
\begin{align*}
4S &= E + E + E + A + B + C + D + E + F + G + H + I\\
&= 3E + (A + B + C) + (D + E + F) + (G + H + I)
\end{align*}  
Remember the three equations $A + B + C = S,\ D + E + F = S,\ G + H + I = S$  
Simplify the previous expression with it, and collect like terms
\begin{align*}
&4S = 3E + (A + B + C) + (D + E + F) + (G + H + I) = 3E + 3S\\
&\Longrightarrow\ 4S = 3E + 3S\\
&\therefore S = 3E
\end{align*}

Hence, it has been demonstrated that the sum for an arbitrary 3 by 3 magic square is 3 times its center value.

## The Proof for Squares
The proof for this fact is arguably simple. It will be a proof by contradiction leveraging the irrationality of the square root of 3.  
So first a quick sidetrack: the irrationality of the square root of 3.

### The Irrationality of $\sqrt{3}$
Suppose, for the sake of contradiction, that $\sqrt{3}$ is rational.  
Then there are some natural numbers $p$ and $q$ such that $\sqrt{3} = \frac{p}{q}$.
Then,
\begin{align*}
\sqrt{3} &= \frac{p}{q}\\
3 &= \frac{p^{2}}{q^{2}}\\
3q^{2} &= p^{2}\\
\end{align*}
$p^{2}$ is a natural number, since $p$ is, and 3 is a prime.  
Thus, by the fundamental theorem of arithmetic, for $p^{2}$ to be a multiple of 3  
$p$ must also be a multiple of 3.
\begin{align*}
p &= 3n\\
3q^{2} &= p^{2}\\
\Rightarrow\ 3q^{2} &= 9n^{2}\\
q^{2} &= 3n^{2}\\
\end{align*}
By the same reason as $p$, $q$ must also be a multiple of 3.  
Thus,
\begin{align*}
q &= 3m\\
\frac{p}{q} = &\frac{3n}{3m} = \frac{n}{m}
\end{align*}
Therefore, if $\sqrt{3}$ could be written as a rational number, then it could
always be written as a rational number with strictly smaller parts ad infinitum.
This seems fine, but this is actually not fine.  
Remember that the set of natural numbers with the standard numeric ordering $\leq$ is a well-ordered set, 
meaning that every non-empty subset contains a least element. This implies that
*no* rational number can have its parts be a strictly descending chain at infinitum.  
Thus, by way of contradiction, the $\sqrt{3}$ can't be rational.


## The Proof for Squares
Now back to magic square of squares.  
Suppose, for the sake of contradiction, that there is a magic square of squares whose sum, let it be $S$, is a perfect square.
$$
\begin{array}{c|c|c}
A & B & C \\ \hline
D & E & F \\ \hline
G & H & I
\end{array}
$$  
$A = a^{2},\ B = b^{2},\ C = c^{2},\ D = d^{2},\ E = e^{2},\ F = f^{2},\ G = g^{2},\ H = h^{2},\ I = i^{2},\ S = s^{2}$  
For some natual number $a, b, c, d, e, f, g, h, i, s$  
Then,
\begin{align*}
S &= 3E\ (\because \text{S is the sum of a magic square})\\
s^{2} &= 3e^{2}\\
\end{align*}  
Dividing both sides by $e^{2}$ we have  
\begin{align*}
&\frac{s^{2}}{e^{2}} = 3\\
&\Rightarrow \left(\frac{s}{e}\right)^{2} = 3\\
&\Rightarrow \frac{s}{e} = \sqrt{3} \\
\end{align*}  
For some natual number e, and s
This, however, is impossible as it contradics the irrationality of $\sqrt{3}$.  
Thus, by way of contradiction, there are no magic square of squares whose sum is also a (perfect) square.

# Observations & Generalizations
The proof for squares seems to be easily generalizable to any even power and with a clever insight to all even perfect powers. This next section does exactly this.

## For All Even Powers
Again, suppose, for the sake of contradiction, that there is a magic square of squares whose sum, let it be $S$, is a perfect even power.
That is
$$
\begin{array}{c|c|c}
A & B & C \\ \hline
D & E & F \\ \hline
G & H & I
\end{array}
$$  
$A = a^{2},\ B = b^{2},\ C = c^{2},\ D = d^{2},\ E = e^{2},\ F = f^{2},\ G = g^{2},\ H = h^{2},\ I = i^{2},\ S = s^{2n}$  
For some natual number $a, b, c, d, e, f, g, h, i, s, n$  
Then,
\begin{align*}
S &= 3E\ (\because \text{S is the sum of a magic square})\\
s^{2n} &= 3e^{2}\\
\end{align*}  
Dividing both sides by $e^{2}$ we have  
\begin{align*}
&\frac{s^{2n}}{e^{2}} = 3\\
&\Rightarrow \frac{(s^{n})^{2}}{e^{2}} = 3\ (\because a^{bc} = (a^{b})^{c})\\
&\Rightarrow \left(\frac{s^{n}}{e}\right)^{2} = 3\\
&\Rightarrow \frac{s^{n}}{e} = \sqrt{3}\\
&\Rightarrow \frac{\sigma}{e} = \sqrt{3}\ (\text{where}\ \sigma := s^{n})
\end{align*}  
As the natural numbers is closed under multiplication, $\sigma = s^{n}$ must also be a natural number.  
Thus, $\frac{\sigma}{e} = \sqrt{3}$ for some natual number e, and $\sigma$.  
This, however, is impossible as it contradics the irrationality of $\sqrt{3}$.  
Thus, by way of contradiction, there are no magic square of squares whose sum is also a (perfect) even power.

## For Odd Powers

A similar proof was thought of for all odd powers, but after further inspection the proof failed, thus, there isn't one for all odd powers.  
In fact, contrary to expectations any odd power can't be disproven to be the sum only leverging the irrationality of $\sqrt{3}$.
There might be other ways of disproving specific odd powers of all odd powers all together.  
Though, I haven't, yet, been successful in finding them.

# Conclusion
With these simple proof the sum for a 3x3 magic square is an odd power, like $1, 2, 3, 5, 6, 7, 8, 10, 11, 12, \text{etc.}$
